export const REFERRAL_SOURCE_SHORTLINK = 'SHORTLINK';
export const REFERRAL_SOURCE_ADS = 'ADS';
export const REFERRAL_DISCOVER_TAB = 'DISCOVER_TAB';
export const REFERRAL_MESSENGER_CODE = 'MESSENGER_CODE';
